import Foundation
import IntentFlowAI

struct FeatureTemplate {
    let name: String
    let mode: IntentFlowMode
    let ui: UIKind

    var contract: String {
        """
        import IntentFlow

        public enum \(name)State: Equatable, Sendable {
            case idle
            case loading
            case failed(message: String)
            case ready
        }

        public enum \(name)Intent: Equatable, Sendable {
            case start
            case retry
            case dismissError
        }

        public enum \(name)Event: Equatable, Sendable {
            case loaded
            case failed(String)
        }

        public enum \(name)Effect: Equatable, Sendable {
            case load
        }

        public enum \(name)Output: Equatable, Sendable {
            case completed
        }

        public enum \(name)Route: Equatable, Sendable {
            case details
        }

        """
    }

    var flow: String {
        """
        import IntentFlow

        public struct \(name)Flow: FlowReducer {
            public init() {}

            public func reduce(
                state: \(name)State,
                signal: FlowSignal<\(name)Intent, \(name)Event>
            ) -> Next<\(name)State, \(name)Effect, \(name)Output, \(name)Route> {
                switch (state, signal) {
                case (.idle, .intent(.start)),
                     (.failed, .intent(.retry)):
                    return .state(.loading)
                        .effect(.load, id: "\(name).load", policy: .cancelInFlight)

                case (.loading, .event(.loaded)):
                    return .state(.ready)
                        .output(.completed)

                case (.loading, .event(.failed(let message))):
                    return .state(.failed(message: message))

                case (.failed, .intent(.dismissError)):
                    return .state(.idle)

                default:
                    return .state(state)
                }
            }
        }

        """
    }

    var effects: String {
        """
        import IntentFlow

        public struct \(name)Effects: FlowEffectHandler {
            public init() {}

            public func handle(_ effect: \(name)Effect) -> AsyncStream<\(name)Event> {
                AsyncStream { continuation in
                    Task {
                        switch effect {
                        case .load:
                            continuation.yield(.loaded)
                            continuation.finish()
                        }
                    }
                }
            }
        }

        """
    }

    var projection: String {
        """
        import IntentFlow

        public struct \(name)ViewState: Equatable, Sendable {
            public let title: String
            public let isLoading: Bool
            public let errorMessage: String?
        }

        public struct \(name)Projection: FlowProjection {
            public init() {}

            public func project(_ state: \(name)State) -> \(name)ViewState {
                switch state {
                case .idle:
                    return .init(title: "\(name)", isLoading: false, errorMessage: nil)
                case .loading:
                    return .init(title: "Loading", isLoading: true, errorMessage: nil)
                case .failed(let message):
                    return .init(title: "Try again", isLoading: false, errorMessage: message)
                case .ready:
                    return .init(title: "Ready", isLoading: false, errorMessage: nil)
                }
            }
        }

        """
    }

    var tests: String {
        """
        import XCTest
        import IntentFlow
        // Add @testable import for your app or feature module when this file lives in a separate test target.

        final class \(name)FlowTests: XCTestCase {
            func testStartRunsLoadEffect() {
                let flow = \(name)Flow()

                let next = flow.reduce(state: .idle, signal: .intent(.start))

                XCTAssertEqual(next.state, .loading)
                XCTAssertEqual(next.effects, [.run(.load, id: "\(name).load", policy: .cancelInFlight)])
            }
        }

        """
    }

    var manifest: String {
        """
        schemaVersion: "0.1"
        feature: "\(name)"
        mode: "\(mode.rawValue)"
        summary: "\(name) generated by IntentFlow."
        states:
          - idle
          - loading
          - failed(message)
          - ready
        intents:
          - start
          - retry
          - dismissError
        events:
          - loaded
          - failed(message)
        effects:
          - load
        routes: []
        outputs:
          - completed
        invariants:
          - "Loading can only be entered by start or retry."
          - "A failed state must keep a user-readable message."
        acceptanceTraces:
          - "idle + start -> loading + load effect"
          - "loading + loaded -> ready + completed output"
        """
    }
}
